language: php
php:
  - '5.6'
  - '7.1'
  - hhvm # on Trusty only
  - nightly
script: build.sh
install:
  - composer install
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS globant_referral;'
